# Generated by Django 4.0 on 2022-01-18 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Orders',
            new_name='Order',
        ),
    ]
