# Generated by Django 4.0 on 2022-01-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_orders_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items_json',
        ),
    ]
