# Generated by Django 4.0 on 2022-01-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_remove_order_items_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items_json',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
